version: "3.5"

services:
    openvpn:
        container_name: "${OPEN_VPN_CONTAINER_NAME}"
        build: ./openvpn-docker
        ports:
            - "1194:1194/udp"
        networks:
            vpn-net:
                ipv4_address: 172.20.0.3
        environment:
            REQ_COUNTRY: "${OPEN_VPN_REQ_COUNTRY}"
            REQ_PROVINCE: "${OPEN_VPN_REQ_PROVINCE}"
            REQ_CITY: "${OPEN_VPN_REQ_CITY}"
            REQ_ORG: "${OPEN_VPN_REQ_ORG}"
            REQ_OU: "${OPEN_VPN_REQ_OU}"
            REQ_CN: ${OPEN_VPN_REQ_CN}
        volumes:
            - ./openvpn/pki:/etc/openvpn/pki
            - ./openvpn/clients:/etc/openvpn/clients
            - ./openvpn/config:/etc/openvpn/config
        cap_add:
            - NET_ADMIN
        restart: unless-stopped

    pihole:
        image: pihole/pihole:latest
        container_name: "${PIHOLE_CONTAINER_NAME}"
        depends_on:
            - "openvpn"
        networks:
            vpn-net:
                ipv4_address: 172.20.0.2
        environment:
            TZ: "Europe/Berlin"
            WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
            DNS1: "${PIHOLE_DNS1}"
            DNS2: "${PIHOLE_DNS2}"
            ServerIP: 172.20.0.2
        volumes:
            - ./pihole/pihole:/etc/pihole
            - ./pihole/dnsmasq.d:/etc/dnsmasq.d
        cap_add:
            - NET_ADMIN
        restart: unless-stopped

networks:
    vpn-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16

